[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
movie_review = "ebJcirbZbURq7M8Bg41ioBgMuAi96yDKFnUQLFh9V1c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sebatustra/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
